spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/consultorios
    username: root
    password: tu_password
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/consultorios
    user: root
    password: tu_password
    locations: classpath:db/migration
