version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: consultorios-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: consultorios
      MYSQL_USER: virginia
      MYSQL_PASSWORD: Lisandro10
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

