spring:
  application:
    name: consultorios


  r2dbc:
    url: ${DB_R2DBC_URL:r2dbc:mysql://localhost:3306/consultorios}
    username: ${DB_USERNAME:virginia}
    password: ${DB_PASSWORD:Lisandro10}
    pool:
      enabled: true

  flyway:
    enabled: true
    url: ${DB_JDBC_URL:jdbc:mysql://localhost:3306/consultorios}
    user: ${DB_USERNAME:virginia}
    password: ${DB_PASSWORD:Lisandro10}
    locations: classpath:db/migration
    baseline-on-migrate: true

  main:
    web-application-type: reactive

logging:
  level:
    root: INFO
    org.springframework.r2dbc: INFO
    org.springframework.security: INFO
    org.springframework.context.annotation: INFO


security:
  jwt:
#    secret: ${JWT_SECRET}
    secret: 12345678901234567890123456789012
    expiration-minutes: 60

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
  reminders:
    enabled: true
    hours-before: 24
    fixed-delay-ms: 300000
  whatsapp:
    enabled: false
    provider: meta # meta | twilio | none
    meta:
      base-url: ${APP_WA_META_BASE_URL:https://graph.facebook.com/v20.0}
      phone-number-id: ${APP_WA_META_PHONE_NUMBER_ID:}
      token: ${APP_WA_META_TOKEN:}
    twilio:
      base-url: ${APP_WA_TWILIO_BASE_URL:https://api.twilio.com}
      account-sid: ${APP_WA_TWILIO_ACCOUNT_SID:}
      auth-token: ${APP_WA_TWILIO_AUTH_TOKEN:}
      from: ${APP_WA_TWILIO_FROM:}
